### ISSUE TITLE
Add pong test -- alive reporting from simplomon

### ISSUE THREAD

**Issue by jpmens** [berthubert/simplomon#19]
I'd like to see simplomon being able to inform me via notifyer that it's alive, and since `ping` checks other servers, maybe `pong` (inspired from Ansible's `ping` which reponds with `pong`) could do so with a configurable interval, e.g. 3600 seconds.

**Comment by berthubert** [comment]
I think this is dailyChime{} which we already have? Or a request for hourlyChime{}?
```lua
dailyChime{utcHour=10} -- 10AM UTC chime confirms monitoring works
```
