### ISSUE TITLE
extra quote in pushover message

### ISSUE THREAD

**Issue by reinoud** [berthubert/simplomon#37]
in my configuration I have stated https{url="https://mywebsite.com"}

When I get an alert (with Pushover) I get the alert:

`https: [ipv4] Unable to retrieve URL 'https://mywebsite.com': SSL peer certificate or SSH remote key was not OK
`
In the (iPhone) Pushover app, the URL is a clickable link. When I click that link, the browser tries to open

`https://snappass.leeuwen.net'
`
(including the extra ' at the end), which is not a valid URL.

**Comment by jpmens** [comment]
I don't see the single quote [anywhere in the source](https://github.com/berthubert/simplomon/blob/b8b4ecc53a10ac0a117d979e186e269da56ecf41/notifiers.cc#L16). Are you sure it's not part of the payload you're transmitting?

An example would possible help. :)

**Comment by job** [comment]
I think the single quotes are set here: https://github.com/berthubert/simplomon/blob/main/minicurl.cc#L147

**Comment by jpmens** [comment]
Thanks, @job; goes to show I should shut up when clueless. I might have been thrown by OP saying "clickable link in the Pushover app", hence my thinking it was the payload, not taking into account the payload is generated.

**Comment by reinoud** [comment]
sorry for the confusion, I tried to not make any assumptions. So I did my best to describe the exact problem :-)

**Comment by reinoud** [comment]
> @reinoud does this fix it?

I don't have a build environment here so I cannot test it
